let cars = [
  {
    compacts: "compact",
    img: "../images/car1.png",
    name: "Ford Fiesta",
    type: "Economy Car",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    compacts: "compact",
    img: "../images/car2.png",
    name: "Nissan Versa",
    type: "Compact Car",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    compacts: "compact",
    name: "Toyota Corolla",
    type: "Mid-size Car",
    img: "../images/car3.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    compacts: "compact",
    name: "Nissan Rogue",
    type: "Mid-size SUV",
    img: "../images/car4.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    compacts: "compact",
    name: "Chevy Traverse",
    type: "Full-size SUV ",
    img: "../images/car5.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    compacts: "compact",
    name: "Nissan Altima",
    type: "Full-size Car",
    img: "../images/car6.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    sport: "sport",
    name: "Royce rolls ghost",
    type: "Full-size Car",
    img: "../images/car7.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    sport: "sport",
    name: "Mercedes s class",
    type: "Full-size Car",
    img: "../images/car8.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    sport: "sport",
    name: "Lamborghini urus",
    type: "Mid-size Car",
    img: "../images/car9.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    sport: "sport",
    name: "Mercedes g63 amg",
    type: "Mid-size SUV",
    img: "../images/car10.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },

  {
    vans:"vans",
    name: "15-Passenger Ford Transit ",
    type: "Full-size Car",
    img: "../images/car11.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    vans:"vans",
    name: "Chrysler Pacifica",
    type: "Full-size Car",
    img: "../images/car12.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    vans:"vans",
    name: "Chevy Silverado 4500HD",
    type: "Mid-size Car",
    img: "../images/car13.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    vans:"vans",
    name: "12-Passenger Ford Transit",
    type: "Mid-size SUV",
    img: "../images/car14.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    vans:"vans",
    name: "15-Passenger Ford Transit ",
    type: "Mid-size SUV",
    img: "../images/car15.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
  {
    vans:"vans",
    name: "Mercedes-Benz Sprinter",
    type: "Mid-size SUV",
    img: "../images/car16.png",
    imgSite: "../images/site.png",
    imgAuto: "../images/automatic.png",
    imgYears: "../images/years.png",
    imgOil: "../images/oil.png",
  },
];
